package com.sivayahealth.lims.entity;

public enum TaskType {
    CALIBRATION,
    SAMPLE_REVIEW,
    DOCUMENT_REVIEW,
    DOCUMENT_APPROVAL,
    STABILITY_TIMEPOINT,
    REAGENT_EXPIRY_CHECK,
    INSTRUMENT_MAINTENANCE,
    TRAINING,
    CAPA_ACTION,
    DEVIATION_REVIEW,
    OOS_INVESTIGATION,
    GENERAL
}
